[phases.setup]
aptPkgs = [
    "libgtk-3-0",
    "libdbus-glib-1-2",
    "libxt6",
    "libx11-6",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxrandr2",
    "libxrender1",
    "libxtst6",
    "libcairo2",
    "libpango-1.0-0",
    "libatk1.0-0",
    "libgdk-pixbuf-2.0-0",
    "libglib2.0-0",
    "libfreetype6",
    "fontconfig",
    "libgl1",
    "libasound2",
    "libxkbcommon0",
    "libgl1-mesa-dri",
    "libnss3",
    "libnspr4",
    "libicu74",
    "libevent-2.1-7",
    "libexpat1",
    "zlib1g",
    "gcc",
    "libstdc++6"
]
