[phases.setup]
aptPkgs = [
    "libgtk-3-0",
    "libdbus-glib-1-2",
    "libxt6",
    "libx11-6",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxrandr2",
    "libxrender1",
    "libxtst6",
    "cairo",
    "pango",
    "atk",
    "gdk-pixbuf",
    "glib",
    "freetype",
    "fontconfig",
    "libgl1",
    "alsa-lib",
    "libxkbcommon",
    "mesa-dri",
    "nss",
    "nspr",
    "icu",
    "libevent",
    "expat",
    "zlib",
    "gcc",
    "libstdc++"
]
